spring:
  application:
    name: forwarder1
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:sharding.yml
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
sender:
  base-url: http://localhost:8100

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: '*'

chunk-size:
  failback-size: 100
  send-size: 100
