
spring:
  application:
    name: forwarder1

sender:
  base-url: ${SENDER_BASE_URL:http://localhost:8100}

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: '*'
