spring:
  application:
    name: forwarder1
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:3306/${MYSQL_DATABASE}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

sender:
  base-url: ${SENDER_BASE_URL}

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: '*'

chunk-size:
  failback-size: 100
  send-size: 100
