spring:
  application:
    name: forwarder1
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}

sender:
  base-url: ${SENDER_BASE_URL}

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: '*'
